
services:
  api:
    build: .
    container_name: banco360-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - DB_NAME=banco360
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - JWT_SECRET=segredo_super_seguro
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: banco360-db
    environment:
      POSTGRES_DB: banco360
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
